<?php if (! $this->compact): ?>
<div class="controls">
<?= $this->tabs ?>

<h1><?= $this->escape($this->title) ?><?= $this->quickSearch ?></h1>
<span<?php if (! $this->stayHere): ?> data-base-target="_next"<?php endif ?>>
<?= $this->addLink ?>
</span>
<?php if ($this->filterEditor): ?>
<?= $this->filterEditor ?>
<?php endif ?>
<?= $this->table->getPaginator() ?>
</div>
<?php endif ?>

<div class="content<?php if ($this->compact): ?> compact<?php endif ?>"<?php if (! $this->stayHere): ?> data-base-target="_next"<?php endif ?>>
<?= $this->form ?>
<?php if (count($table)): ?>
<?= $this->table->render() ?>
<?php endif ?>
</div>
