<div class="controls">
<?= $this->tabs ?>
<h1><?= $this->escape($this->title) ?></h1>
<span data-base-target="_next">
<?= $this->addLink ?>
</span>
<?php if (count($table) || ($this->filterEditor && ! $this->filterEditor->getFilter()->isEmpty())): ?>
<?= $this->filterEditor ?>
<?php endif ?>
<?= $this->table->getPaginator() ?>
</div>

<div class="content" data-base-target="_next">
<?php if (count($table)): ?>
<?= $this->table->render() ?>
<?php endif ?>
</div>
