language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4snapshot'
  - nightly

services:
  - mysql
  - postgresql

#cache:
#  directories:
#    - vendor

matrix:
  fast_finish: true
  include:
    - env: CHECK=phpcs
      php: nightly # Note: will be allowed failure
    - env: CHECK=phpcs
      php: '7.0'
    - env: CHECK=phpcs
      php: '5.6'
  allow_failures:
    - php: nightly

env:
  - CHECK=phpunit DB=mysql DIRECTOR_TESTDB_RES="Director MySQL TestDB" DIRECTOR_TESTDB="director_test"
  - CHECK=phpunit DB=pgsql DIRECTOR_TESTDB_RES="Director PostgreSQL TestDB" DIRECTOR_TESTDB="director_test"
    DIRECTOR_TESTDB_USER="director_test"

before_script:
  - ./test/setup_vendor.sh
  - '[ "$CHECK" != phpunit ] || ./test/travis-prepare.sh'

script:
  - '[ "$CHECK" != phpcs ] || php vendor/phpcs.phar'
  - '[ "$CHECK" != phpunit ] || php vendor/phpunit.phar --testdox || php vendor/phpunit.phar --verbose'
