language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly

services:
  - mysql
  - postgresql

cache:
  directories:
    - vendor

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

env:
  - DB=mysql DIRECTOR_TESTDB_RES="Director MySQL TestDB" DIRECTOR_TESTDB="director_test"
  - DB=pgsql DIRECTOR_TESTDB_RES="Director PostgreSQL TestDB" DIRECTOR_TESTDB="director_test"
    DIRECTOR_TESTDB_USER="director_test"

before_script:
  - ./test/setup_vendor.sh
  - ./test/travis-prepare.sh

script:
  - php vendor/phpcs.phar --report-width=auto --report-full --report-gitblame --report-summary -p --standard=PSR2 --extensions=php --encoding=utf-8 -w -s library/Director/ library/vendor/ipl/ application/ *.php test
  - php vendor/phpunit.phar --testdox || phpunit --verbose
