language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

services:
  - mysql
  - postgresql

cache:
  directories:
    - vendor

env:
  - DB=mysql DIRECTOR_TESTDB_RES="Director MySQL TestDB" DIRECTOR_TESTDB="director_test"
  - DB=pgsql DIRECTOR_TESTDB_RES="Director PostgreSQL TestDB" DIRECTOR_TESTDB="director_test"
    DIRECTOR_TESTDB_USER="director_test"

before_script:
  - ./test/travis-prepare.sh
  - composer install
