language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly

services:
  - mysql
  - postgresql

cache:
  directories:
    - vendor

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

env:
  - DB=mysql DIRECTOR_TESTDB_RES="Director MySQL TestDB" DIRECTOR_TESTDB="director_test"
  - DB=pgsql DIRECTOR_TESTDB_RES="Director PostgreSQL TestDB" DIRECTOR_TESTDB="director_test"
    DIRECTOR_TESTDB_USER="director_test"

before_script:
  # TODO: Re-enable after dropping 5.3 support:
  # - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
  - curl -OL https://github.com/squizlabs/PHP_CodeSniffer/releases/download/2.9.1/phpcs.phar
  - wget https://github.com/Icinga/icingaweb2/archive/v2.4.0.tar.gz
  - tar xfz v2.4.0.tar.gz
  - ln -s icingaweb2-2.4.0/library/Icinga
  - ln -s icingaweb2-2.4.0/library/vendor/Zend
  - ./test/travis-prepare.sh

script:
  - php phpcs.phar --report-width=auto --report-full --report-gitblame --report-summary -p --standard=PSR2 --extensions=php --encoding=utf-8 -w -s library/Director/ application/ configuration.php run.php test
  - phpunit --testdox || phpunit --verbose
