<div class="controls">
<?= $this->tabs ?>
</div>

<div class="content">
<?php if ($this->errorMessage): ?>
<p class="error"><?= $this->errorMessage ?></p>
<?php endif ?>
<?= $this->form ?>
<?php if (empty($this->dashboards)): ?>
<?= $this->translate('No dashboard available, you might have not enough permissions') ?>
<?php endif ?>
<?php foreach ($this->dashboards as $dashboard): ?>
<?= $dashboard ?>
<?php endforeach ?>
</div>
