<div class="controls">
<?= $this->tabs ?>
<h1><?= $this->escape($this->title) ?></h1>
<span class="action-links"<?php if (! $this->stayHere): ?> data-base-target="_next"<?php endif ?>>
<?= $this->addLink ?>
</span>
<?= $this->filterEditor ?>
<?= $this->table->getPaginator() ?>
</div>

<div class="content"<?php if (! $this->stayHere): ?> data-base-target="_next"<?php endif ?>>
<?php if ($this->run): ?>
<h3><?= $this->translate('Sync run details') ?></h3>
<?= $this->render('syncrule/syncRunDetails.phtml') ?>
<?php endif ?>
<div data-base-target="_main">
<?= $this->table->render() ?>
</div>
</div>
