<table class="key-value-table">
 <tr>
  <th><?= $this->translate('Start time') ?></th>
  <td><?= $this->escape($run->start_time) ?></td>
 </tr>
 <tr>
  <th><?= $this->translate('Duration') ?></th>
  <td><?= sprintf('%.2fs', $run->duration_ms / 1000) ?></td>
 </tr>
 <tr>
  <th><?= $this->translate('Activity') ?></th>
  <td data-base-target="_next"><?= $this->render('syncrule/runSummary.phtml') ?></td>
 </tr>
</table>
