<div class="controls">
<?= $this->tabs ?>
<h1><?= $this->escape($this->title) ?></h1>
<span class="action-links">
<?= $this->actionLinks ?>
</span>
</div>

<div class="content">
This is a service template. [As it has no command You might want to assign it:

<ul>
<li>Assign it to one or more single hosts</li>
<li>Assign it to all hosts inheriting a specific template</li>
<li>Assign it base on rule/rule definitions

Admin tasks:
<ul>
<li>Control which fields (custom vars) can be filled by your users
<li>Provide sets of services
</ul>
</div>
