<div class="controls">
<?= $this->tabs ?>
<h1><?= $this->escape($this->title) ?></h1>
</div>

<div class="content">
<?php if ($this->objects): ?>
<table class="common-table table-row-selectable" data-base-target="_next">
 <thead><tr><th><?= $this->translate('Object name') ?></th></tr></thead>
 <tbody>
<?php foreach ($this->objects as $object): ?>
  <tr><td><?= $this->qlink(
    str_replace('!', ': ', $object),
    'director/inspect/object',
    array(
        'endpoint' => $this->endpoint,
        'type'     => $this->type->name,
        'plural'   => $this->type->plural_name,
        'name'     => $object
    )
  ) ?></td></tr>
<?php endforeach ?>
 </tbody>
</table>
<?php endif ?>
<pre><?= $this->renderPlainObject($this->type) ?></pre>
</div>
