<div class="controls">
<?= $this->tabs ?>
<h1><?= $this->escape($this->title) ?></h1>
</div>

<div class="content">
<?php
$cert   = $this->escape($this->certname);
$master = $this->escape($this->master);
?>
<p>Please check the <a href="http://docs.icinga.org/icinga2/latest/doc/module/icinga2/chapter/icinga2-client">Icinga 2 Client documentation</a> for more related information. The Director-assisted setup corresponds to configuring the <a href="http://docs.icinga.org/icinga2/latest/doc/module/icinga2/chapter/icinga2-client#icinga2-client-configuration-command-bridge">Client as Command Execution Bridge</a>.</p>

<?php if ($this->error): ?>
<p class="error"><?= $this->escape($this->error) ?></p>
</div>
<?php return; endif ?>

<h2>For manual configuration</h2>
<p>Ticket : <code><?= $this->escape($ticket) ?></code></p>
<h2>Windows Kickstart Script</h2>
<?= $this->qlink(
    'Download',
    $this->url()->with('download', 'windows-kickstart'),
    null,
    array('class' => 'icon-download', 'target' => '_blank')
) ?>
<pre style="background: black; color: white; height: 14em; overflow: scroll;">
<?= $this->escape($this->windows) ?>
</pre>
<p><?= $this->translate(
    'This requires the Icinga Agent to be installed. It generates and signs'
    . ' it\'s certificate and it also generates a minimal icinga2.conf to get'
    . ' your agent connected to it\'s parents'
) ?></p>
<h2>Linux commandline</h2>
<?= $this->qlink(
    'Download',
    $this->url()->with('download', 'linux'),
    null,
    array('class' => 'icon-download', 'target' => '_blank')
) ?>
<p>Just download and run this script on your Linux Client Machine:</p>
<pre style="background: black; color: white; height: 14em; overflow: scroll;">
<?= $this->escape($this->linux) ?>
</pre>
</div>
