<div class="controls">
<?= $this->tabs ?>
<h1><?= $this->escape($this->title) ?></h1>
<span class="action-links">
<?= $this->addLink ?>
</span>
</div>

<div class="content">
<?= $this->form ?>
<?php foreach ($this->tables as $key => $table): ?>
<?php if (count($table)): ?>
<?php if ($key === 0 || $key === 1): ?>
<?= $table->render() ?>
<?php else: ?>
<div data-base-target="_next">
<?= $table->render() ?>
</div>
<?php endif ?>
<?php endif ?>
<?php endforeach ?>
</div>
