<div class="controls">
<?= $this->tabs ?>
<h1><?= $this->escape($this->title) ?></h1>
<span<?php if (! $this->stayHere): ?> data-base-target="_next"<?php endif ?>>
<?= $this->addLink ?>
</span>
<?= $this->filterEditor ?>
<?= $this->table->getPaginator() ?>
</div>

<div class="content"<?php if (! $this->stayHere): ?> data-base-target="_next"<?php endif ?>>
<?= $this->form ?>
<?= $this->table->render() ?>
</div>
