<div class="controls">
<?= $this->tabs ?>
<h1><?= $this->escape($this->title) ?></h1>
<span class="action-links">
<?= $this->actionLinks ?>
</span>
</div>

<div class="content">
<?php if ($this->object->isDisabled()): ?>
<p class="error"><?= $this->translate('This object will not be deployed as it has been disabled') ?></p>
<?php endif ?>
<?php if ($this->isExternal): ?>
<p><?= $this->translate(
    'This is an external object. It has been imported from Icinga 2 throught the'
    . ' Core API and cannot be managed with the Icinga Director. It is however'
    . ' perfectly valid to create objects using this or referring to this object.'
    . ' You might also want to define related Fields to make work based on this'
    . ' object more enjoyable'
) ?></p>
<?php endif ?>
<?php foreach ($this->config->getFiles() as $filename => $file): ?>
<?php if (! $this->isExternal): ?><h2><?= $this->escape($filename) ?></h2><?php endif ?>
<pre<?php if ($this->object->isDisabled()): ?> class="disabled"<?php elseif ($this->isExternal): ?> class="logfile"<?php endif ?>>
<?= $this->escape($file->getContent()) ?>
</pre>
<?php endforeach ?>

</div>
