<div class="controls">
<?= $this->tabs ?>
<h1><?= $this->escape($this->title) ?></h1>
</div>

<div class="content">
<?php if ($object->disabled === 'y'): ?>
<p class="error"><?= $this->translate('This object will not be deployed as it has been disabled') ?></p>
<?php endif ?>
<pre<?php if ($object->disabled === 'y'): ?> class="disabled"<?php endif ?>><?= $this->escape($object) ?><?php if ($this->extraObjects): ?>
<?= implode('', $this->extraObjects) ?>
<?php endif ?></pre>
</div>
