<div class="controls">
<?= $this->tabs ?>
<h1><?= $this->escape($this->title) ?></h1>
</div>

<div class="content">
<p><?= $this->escape($source->description) ?></p>
<?php if ($source->import_state === 'unknown'): ?>
<p><?= $this->translate(
    "It's currently unknown whether we are in sync with this Import Source."
    . ' You should either check for changes or trigger a new Import Run.'
) ?></p>
<?php elseif ($source->import_state === 'in-sync'): ?>
<p><?= sprintf(
    $this->translate(
        'This Import Source was last found to be in sync at %s.'
    ),
    $source->last_attempt
) /*
TODO: check whether...
      - there have been imports since then, differing from former ones
      - there have been activities since then
*/ ?></p>
<?php elseif ($source->import_state === 'pending-changes'): ?>
<p class="warning"><?= $this->translate(
    'There are pending changes for this Import Source. You should trigger a new'
    . ' Import Run.'
) ?></p>
<?php elseif ($source->import_state === 'failing'): ?>
<p class="error"><?= sprintf(
    $this->translate(
        'This Import Source failed when last checked at %s: %s'
    ),
    $source->last_attempt,
    $source->last_error_message
) /*
TODO: check whether...
      - there have been imports since then, differing from former ones
      - there have been activities since then
*/ ?></p>
<?php endif ?>
<?= $this->checkForm ?>
<?= $this->runForm ?>

</div>
