<div class="controls">
<?= $this->tabs ?>
<h1><?= $this->escape($this->title) ?></h1>
<span class="action-links" data-base-target="_next">
<?= $this->addLink ?>
</span>
<?php if (count($table) || ($this->filterEditor && ! $this->filterEditor->getFilter()->isEmpty())): ?>
<?= $this->filterEditor ?>
<?php endif ?>
<?= $this->table->getPaginator() ?>
</div>

<div class="content" data-base-target="_next">
<table class="name-value-table">
 <tr>
  <th><?= $this->translate('Actions') ?></th>
  <td data-base-target="_self"><?=  $this->deployForm ?><br /><?= $this->qlink(
    $this->translate('Last related activity'),
    'director/show/activitylog',
    array('checksum' => $this->config->getLastActivityHexChecksum()),
    array('class' => 'icon-clock', 'data-base-target' => '_next')
  ) ?><br /><?= $this->qlink(
    $this->translate('Diff with other config'),
    'director/config/diff',
    array('left' => $this->config->getHexChecksum()),
    array('class' => 'icon-flapping', 'data-base-target' => '_self')
  ) ?></td>
 </tr>
 <tr>
  <th><?= $this->translate('Statistics') ?></th>
  <td><?= sprintf(
      $this->translate('%d files rendered in %0.2fs'),
      count($this->config->getFiles()),
      $config->getDuration() / 1000
  ) ?></td>
 </tr>
</table>

<?php if (count($table)): ?>
<div data-base-target="_self">
<?= $this->table->render() ?>
</div>
<?php endif ?>
</div>
