<div class="controls">
<?= $this->tabs ?>
<h1><?= $this->escape($this->title) ?></h1>
</div>

<div class="content">
<div class="pagination-control">
<ul class="nav tab-nav">
  <li class="nav-item"><?php if ($this->neighbors->prev): ?>
 <a href="<?= $this->url()->with('id', $this->neighbors->prev) ?>"><?=
   $this->icon('angle-double-left')
 ?></a>
<?php else: ?>
<span class="disabled"><?= $this->icon('angle-double-left') ?></span>
<?php endif ?>
</li><li>
<?php if ($this->neighbors->next): ?>
 <a href="<?= $this->url()->with('id', $this->neighbors->next) ?>"><?=
   $this->icon('angle-double-right')
 ?></a>
<?php else: ?>
 <span class="disabled"><?= $this->icon('angle-double-right') ?></span>
<?php endif ?>
</li>
</div>
<?= $this->output ?>
</div>
