<h2><?= sprintf(
    '%s "%s" has been modified',
    ucfirst(preg_replace('/^icinga_/', '', $entry->object_type)),
    $entry->object_name
) ?></h2>

<table class="log-properties">
<!-- TODO: diff, old/new class -->
<tr><td style="vertical-align: top; width: 50%">
<h3><?= $this->translate('Former state') ?></h3>
<pre><?= $this->escape((string) $this->oldObject) ?></pre>
</td><td style="vertical-align: top; width: 50%">
<h3><?= $this->translate('New object') ?></h3>
<pre><?= $this->escape((string) $this->newObject) ?></pre>
</td></tr>
</table>

