name: PHP Tests

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Static analysis for php ${{ matrix.php }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3', '8.4', '8.5']
        os: ['ubuntu-latest']

    steps:
      - name: Checkout code base
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phpcs:3

      - name: Setup dependencies
        run: composer require -n --no-progress overtrue/phplint phpunit/phpunit

      - name: PHP Lint
        if: ${{ ! cancelled() }}
        run: ./vendor/bin/phplint -n --exclude={^vendor/.*} -- .

      - name: PHP CodeSniffer
        if: ${{ ! cancelled() }}
        run: phpcs

  test:
    name: Unit tests with php ${{ matrix.php }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3', '8.4', '8.5']
        os: ['ubuntu-latest']

    services:
      mysql:
        image: mariadb
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: director_test
          MYSQL_USER: director_test
          MYSQL_PASSWORD: director_test
        options: >-
          --health-cmd "mariadb -s -uroot -proot -e'SHOW DATABASES;' 2> /dev/null | grep director_test > test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3306/tcp

      pgsql:
        image: postgres
        env:
          POSTGRES_USER: director_test
          POSTGRES_PASSWORD: director_test
          POSTGRES_DB: director_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432/tcp

    steps:
      - name: Checkout code base
        uses: actions/checkout@v6

      - name: Setup PHP and Icinga PHP libraries
        uses: Icinga/github-actions/.github/actions/php-and-dependencies@main
        with:
          php-version: ${{ matrix.php }}
          php-extensions: mysql, pgsql
          php-tools: phpunit:9.5
          dependencies: |
            {
              "./vendor/icinga-php/legacy": "https://github.com/Icinga/icinga-php-legacy.git#snapshot",
              "./vendor/icingaweb2/modules/icingadb": "https://github.com/Icinga/icingadb-web.git"
            }

      - name: PHPUnit with MySQL
        if: ${{ ! cancelled() }}
        env:
          ICINGAWEB_CONFIGDIR: test/config
          DIRECTOR_TESTDB_RES: Director MySQL TestDB
          DIRECTOR_TESTDB: director_test
          DIRECTOR_TESTDB_HOST: 127.0.0.1
          DIRECTOR_TESTDB_PORT: ${{ job.services.mysql.ports['3306'] }}
          DIRECTOR_TESTDB_USER: director_test
          DIRECTOR_TESTDB_PASSWORD: director_test
        run: phpunit --verbose --bootstrap "$PHPUNIT_BOOTSTRAP"

      - name: PHPUnit with PostgreSQL
        if: ${{ ! cancelled() }}
        env:
          ICINGAWEB_CONFIGDIR: test/config
          DIRECTOR_TESTDB_RES: Director PostgreSQL TestDB
          DIRECTOR_TESTDB: director_test
          DIRECTOR_TESTDB_HOST: 127.0.0.1
          DIRECTOR_TESTDB_PORT: ${{ job.services.pgsql.ports['5432'] }}
          DIRECTOR_TESTDB_USER: director_test
          DIRECTOR_TESTDB_PASSWORD: director_test
        run: phpunit --verbose --bootstrap "$PHPUNIT_BOOTSTRAP"
