name: PHPStan

on:
  pull_request:

jobs:
  phpstan:
    uses: icinga/github-actions/.github/workflows/phpstan.yml@main
    with:
      dependencies: |
        {
         "/icingaweb2"                             : "https://github.com/Icinga/icingaweb2.git",
         "/usr/share/icingaweb2-modules/icingadb"  : "https://github.com/Icinga/icingadb-web.git",
         "/usr/share/icingaweb2-modules/cube"      : "https://github.com/Icinga/icingaweb2-module-cube.git",
         "/usr/share/icingaweb2-modules/incubator" : "-b stable/0.22.0 https://github.com/Icinga/icingaweb2-module-incubator"
        }
